// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

contract BaseConfig {
  enum DexName {
    SwaapV2, // 0
    Bebop, // 1
    Native, // 2
    KyberLO,
    KyberDSLO,
    UNI,
    KyberDMM,
    Velodrome,
    Fraxswap,
    Camelot,
    StableSwap,
    GMX,
    Mantis,
    Wombat,
    WooFiV2,
    Smardex,
    SolidlyV2,
    NomiswapStable,
    BancorV3,
    Curve,
    PancakeStableSwap,
    UniV3ProMM,
    RFQ,
    BalancerV2,
    DODO,
    Synthetix,
    Hashflow,
    PSM,
    WSTETH,
    StEth,
    Platypus,
    Maverick,
    SyncSwap,
    AlgebraV1,
    BalancerBatch,
    iZiSwap,
    TraderJoeV2,
    LevelFiV2,
    GMXGLP,
    Vooi,
    VelocoreV2,
    MaticMigrate,
    Kokonut,
    BalancerV1,
    ArbswapStable,
    BancorV2,
    Ambient,
    UniV1,
    LighterV2,
    EtherFieETH,
    EtherFiWeETH,
    Kelp,
    EthenaSusde,
    RocketPool,
    MakersDAI,
    Renzo,
    WBETH,
    MantleETH,
    FrxETH,
    SfrxETH,
    SfrxETHConvertor,
    SwellETH,
    RswETH,
    StaderETHx,
    OriginETH,
    PrimeETH,
    MantleUsd,
    BedrockUniETH,
    MaiPSM,
    PufferFinance,
    SymbioticLRT
  }
}
